### PR TITLE
(FACT-2633) Relax rubocop dependancy

### PR DESCRIPTION
**Pull request by oanatmaria**
- Fix new cops offences
- Ruby 2.3 is not supported by newer versions of rubocop

### CODE REVIEW

**Comment by gimmyxd** [comment]
Making this changes means that Puppet as a gem will not be able to run on Ruby 2.3(due to the missing methods like `match?`) 
- https://apidock.com/ruby/v2_4_6/String/match%3F

- https://github.com/puppetlabs/puppet/blob/master/.gemspec#L21

I think also PDK is using older versions of Ruby.

**Comment by oanatmaria** [comment]
@gimmyxd yes, you are right. This PR won't be merged (marked with do not merge) until we drop support for ruby 2.3 in puppet.

**Comment by joshcooper** [comment]
I filed https://tickets.puppetlabs.com/browse/PUP-10509 to drop old ruby versions in Puppet Platform 7. Until then maybe target ruby 2.3 language features and disable the cop?

**Comment by IrimieBogdan** [comment]
We will continue to support Ruby 2.3

**Pull request closed without merging**
